server:
  port: 8802
spring:
  application:
    name: department-service


eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8800/eureka/

management:
  security:
    enabled: false

info:
  component: department-service

