server:
  port: 9901

# 配置输入 /info 显示的消息
info:
  component: gateway-service


management:
  security:
    enabled: false

# 配置应用名称及服务名
spring:
  application:
    name: gateway-service

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://locahost:8800/eureka/
    prefer-same-zone-eureka: true               # 服务端和客户端在同一个zone下
    registry-fetch-interval-seconds: 30         # 隔多久对去服务器拉去信息：默认30秒
    eureka-server-read-timeout-seconds: 5       # 读取超时前等待时间
    eureka-server-connect-timeout-seconds: 5    # 连接超时前等待时间
    eureka-server-total-connections: 500        # 允许连接server最大数量

  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true                     # 显示ip地址
    lease-renewal-interval-in-seconds: 30 		# 续约更新时间间隔（默认30秒）:注册慢
    lease-expiration-duration-in-seconds: 90   	# 续约到期时间（默认90秒）
#    environment: dev                           # 指定环境

zuul:
#  ignored-services: *

  prefix: /api
  routes:
    composite-service:
      path: /composite-service/**
      service-id: composite-service
    employee-service:
      path: /employee-service/**
      service-id: employee-service

    department-service:
      path: /department-service/**
      service-id: employee-service



