server:
  port: 9900
spring:
  application:
    name: composite-service
management:
  security:
    enabled: false

feign:
  hystrix:
    enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 50  #并发执行的最大线程数，默认10

  command:
    paas-file:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3600000
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  #命令执行超时时间，默认1000ms


eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8800/eureka/
    registry-fetch-interval-seconds: 10  #从服务器列表获得信息间隔
info:
  component: composite-service


